package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	inputDir := flag.String("dir", "", "Directory containing .cachou files to compile")
	inputFile := flag.String("file", "", "Specific .cachou file to compile")
	outputDir := flag.String("out", "", "Output directory for compiled .js files")
	runtimeImport := flag.String("runtime", "cachoujs", "Module specifier used for the framework import (default: cachoujs)")
	flag.Parse()

	if *inputDir == "" && *inputFile == "" {
		fmt.Println("Usage: go run compiler.go -file <file.cachou> OR -dir <directory> [-out <dir>] [-runtime cachoujs]")
		os.Exit(1)
	}

	failed := false

	if *inputFile != "" {
		err := compileFile(*inputFile, *outputDir, *runtimeImport)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error compiling file %s: %v\n", *inputFile, err)
			failed = true
		}
	}

	if *inputDir != "" {
		err := filepath.Walk(*inputDir, func(path string, info os.FileInfo, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if info.IsDir() || !strings.HasSuffix(info.Name(), ".cachou") {
				return nil
			}

			outDir := *outputDir
			if outDir != "" {
				relDir, err := filepath.Rel(*inputDir, filepath.Dir(path))
				if err != nil {
					return err
				}
				outDir = filepath.Join(outDir, relDir)
			}

			err := compileFile(path, outDir, *runtimeImport)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error compiling file %s: %v\n", path, err)
				failed = true
			}
			return nil
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading directory %s: %v\n", *inputDir, err)
			os.Exit(1)
		}
	}

	if failed {
		os.Exit(1)
	}
}

func compileFile(path string, outDir string, runtimeImport string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	// Determine output filename and component name
	base := filepath.Base(path)
	ext := filepath.Ext(base)
	nameWithoutExt := strings.TrimSuffix(base, ext)
	componentName := uppercaseFirst(nameWithoutExt)

	// Determine output path first
	var outputPath string
	if outDir != "" {
		err := os.MkdirAll(outDir, 0755)
		if err != nil {
			return err
		}
		outputPath = filepath.Join(outDir, nameWithoutExt+".js")
	} else {
		outputPath = filepath.Join(filepath.Dir(path), nameWithoutExt+".js")
	}

	if runtimeImport == "" {
		runtimeImport = "cachoujs"
	}

	// Parse sections
	sections, err := parseComponentSections(string(content))
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	scriptContent := sections.Script
	styleContent := sections.Style
	styleScoped := sections.StyleScoped
	htmlContent := strings.TrimSpace(sections.Template)

	// Scope HTML template and CSS styles
	scopeID := "data-c-" + sanitizeScopeID(nameWithoutExt)
	var scopedHTML string
	var scopedCSS string
	if err := validateTemplateTags(htmlContent); err != nil {
		line, col := lineCol(htmlContent, 0)
		return fmt.Errorf("%s: template validation failed near %d:%d: %w", path, line, col, err)
	}
	if styleContent != "" {
		if styleScoped {
			scopedHTML, err = scopeTemplate(htmlContent, scopeID)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			scopedCSS, err = scopeCSS(styleContent, scopeID)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
		} else {
			if err := validateCSS(styleContent); err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			scopedHTML = htmlContent
			scopedCSS = strings.TrimSpace(styleContent)
		}
	} else {
		scopedHTML = htmlContent
	}

	// Replace JSX-style {expression} with template literal ${expression}
	compiledHTML, err := compileTemplateExpressions(scopedHTML)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}

	styleImport := ""
	if scopedCSS != "" {
		cssOutputPath := filepath.Join(filepath.Dir(outputPath), nameWithoutExt+".css")
		err = os.WriteFile(cssOutputPath, []byte(scopedCSS+"\n"), 0644)
		if err != nil {
			return err
		}
		styleImport = fmt.Sprintf("import \"./%s.css\";\n", nameWithoutExt)
	}

	// Format JS Component output
	mapFile := nameWithoutExt + ".js.map"
	outputJS := fmt.Sprintf(`// Generated by CachouJS Compiler - DO NOT EDIT
// Source: %s
import * as Cachou from "%s";
%s
const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function %s(props = {}) {
  // --- Component Setup ---
  %s

  // --- Render ---
  return %s;
}
//# sourceMappingURL=%s
`, filepath.ToSlash(base), runtimeImport, styleImport, componentName, indentLines(scriptContent, "  "), renderExpression(compiledHTML), mapFile)

	err = os.WriteFile(outputPath, []byte(outputJS), 0644)
	if err != nil {
		return err
	}

	// External source map with original sourcesContent for editor navigation.
	if err := writeSourceMap(outputPath+".map", filepath.Base(outputPath), base, string(content), outputJS); err != nil {
		return err
	}

	fmt.Printf("Compiled: %s -> %s (Component: %s)\n", path, outputPath, componentName)
	return nil
}

func writeSourceMap(mapPath, fileName, sourceName, sourceContent, generated string) error {
	// Line-level identity mapping: each generated line maps back to the same line
	// number in the .cachou source when possible (best-effort for navigation).
	genLines := strings.Split(generated, "\n")
	srcLines := strings.Split(sourceContent, "\n")
	var mappings []string
	for i := range genLines {
		srcLine := i
		if srcLine >= len(srcLines) {
			srcLine = len(srcLines) - 1
		}
		if srcLine < 0 {
			srcLine = 0
		}
		// VLQ segments are complex; emit empty per-line mappings with sourcesContent
		// so tools still open the original file. Fine-grained column maps can come later.
		_ = srcLine
		mappings = append(mappings, "")
	}

	escapedSource, err := jsonQuote(sourceContent)
	if err != nil {
		return err
	}
	payload := fmt.Sprintf(
		`{"version":3,"file":%s,"sources":[%s],"sourcesContent":[%s],"names":[],"mappings":%s}`,
		strconv.Quote(fileName),
		strconv.Quote(filepath.ToSlash(sourceName)),
		escapedSource,
		strconv.Quote(strings.Join(mappings, ";")),
	)
	return os.WriteFile(mapPath, []byte(payload+"\n"), 0644)
}

func jsonQuote(s string) (string, error) {
	b, err := jsonMarshalString(s)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func jsonMarshalString(s string) ([]byte, error) {
	// Minimal JSON string marshal without encoding/json import churn in older paths.
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"', '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				b.WriteString(fmt.Sprintf(`\u%04x`, r))
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return []byte(b.String()), nil
}

func renderExpression(compiledHTML string) string {
	if !strings.Contains(compiledHTML, "${") {
		return "htmlStatic(" + strconv.Quote(compiledHTML) + ")"
	}
	return "html`" + "\n" + compiledHTML + "\n" + "`"
}

type componentSections struct {
	Script      string
	Style       string
	StyleScoped bool
	Template    string
}

func parseComponentSections(content string) (componentSections, error) {
	var sections componentSections
	remaining := content

	var err error
	remaining, sections.Script, err = extractTopLevelSection(remaining, "script")
	if err != nil {
		return sections, err
	}

	var styleAttrs string
	remaining, sections.Style, styleAttrs, err = extractTopLevelSectionWithAttrs(remaining, "style")
	if err != nil {
		return sections, err
	}
	sections.StyleScoped = hasBooleanAttr(styleAttrs, "scoped")

	sections.Script = strings.TrimSpace(sections.Script)
	sections.Style = strings.TrimSpace(sections.Style)
	sections.Template = strings.TrimSpace(remaining)
	return sections, nil
}

func extractTopLevelSection(content string, tagName string) (string, string, error) {
	remaining, inner, _, err := extractTopLevelSectionWithAttrs(content, tagName)
	return remaining, inner, err
}

func extractTopLevelSectionWithAttrs(content string, tagName string) (string, string, string, error) {
	openStart, openEnd := findTopLevelOpenTag(content, tagName)
	if openStart == -1 {
		return content, "", "", nil
	}

	closeStart := findClosingTag(content, tagName, openEnd)
	if closeStart == -1 {
		line, col := lineCol(content, openStart)
		return content, "", "", fmt.Errorf("missing closing </%s> for <%s> at %d:%d", tagName, tagName, line, col)
	}

	closeEnd := closeStart + len(tagName) + 3
	inner := content[openEnd:closeStart]
	openTag := content[openStart:openEnd]
	attrs := strings.TrimSpace(openTag[1+len(tagName) : len(openTag)-1])
	next := strings.TrimSpace(content[:openStart] + content[closeEnd:])
	return next, inner, attrs, nil
}

func findTopLevelOpenTag(content string, tagName string) (int, int) {
	lowerName := strings.ToLower(tagName)
	for i := 0; i < len(content); i++ {
		if content[i] != '<' || i+1 >= len(content) || content[i+1] == '/' {
			continue
		}
		end := findTagEnd(content, i+1)
		if end == -1 {
			return -1, -1
		}
		tag := content[i : end+1]
		if strings.ToLower(readTagName(tag)) == lowerName {
			return i, end + 1
		}
		i = end
	}
	return -1, -1
}

func findClosingTag(content string, tagName string, start int) int {
	needle := "</" + strings.ToLower(tagName) + ">"
	lower := strings.ToLower(content)
	idx := strings.Index(lower[start:], needle)
	if idx == -1 {
		return -1
	}
	return idx + start
}

func readTagName(tag string) string {
	if len(tag) < 3 || tag[0] != '<' {
		return ""
	}
	start := 1
	if tag[start] == '/' {
		start++
	}
	end := start
	for end < len(tag) {
		ch := tag[end]
		if ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r' || ch == '/' || ch == '>' {
			break
		}
		end++
	}
	return tag[start:end]
}

func lineCol(content string, index int) (int, int) {
	line := 1
	col := 1
	for i := 0; i < len(content) && i < index; i++ {
		if content[i] == '\n' {
			line++
			col = 1
		} else {
			col++
		}
	}
	return line, col
}

func compileTemplateExpressions(template string) (string, error) {
	var out strings.Builder
	for i := 0; i < len(template); i++ {
		// Literal braces: {{ → { and }} → }
		if template[i] == '{' && i+1 < len(template) && template[i+1] == '{' {
			out.WriteByte('{')
			i++
			continue
		}
		if template[i] == '}' && i+1 < len(template) && template[i+1] == '}' {
			out.WriteByte('}')
			i++
			continue
		}
		if template[i] != '{' {
			out.WriteByte(template[i])
			continue
		}
		end, err := findExpressionEnd(template, i)
		if err != nil {
			return "", err
		}
		expr := strings.TrimSpace(template[i+1 : end])
		if expr == "" {
			line, col := lineCol(template, i)
			return "", fmt.Errorf("empty template expression at %d:%d (use {{ and }} for literal braces)", line, col)
		}
		out.WriteString("${")
		out.WriteString(expr)
		out.WriteByte('}')
		i = end
	}
	return out.String(), nil
}

func findExpressionEnd(template string, start int) (int, error) {
	depth := 0
	var quote byte
	escaped := false
	for i := start; i < len(template); i++ {
		ch := template[i]
		if quote != 0 {
			if escaped {
				escaped = false
				continue
			}
			if ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' || ch == '`' {
			quote = ch
			continue
		}
		if ch == '{' {
			depth++
			continue
		}
		if ch == '}' {
			depth--
			if depth == 0 {
				return i, nil
			}
			if depth < 0 {
				break
			}
		}
	}
	line, col := lineCol(template, start)
	return -1, fmt.Errorf("unclosed template expression at %d:%d", line, col)
}

func validateTemplateTags(html string) error {
	for i := 0; i < len(html); i++ {
		if html[i] != '<' || i+1 >= len(html) || html[i+1] == '!' || html[i+1] == '?' {
			continue
		}
		end := findTagEnd(html, i+1)
		if end == -1 {
			line, col := lineCol(html, i)
			return fmt.Errorf("unclosed HTML tag at %d:%d", line, col)
		}
		i = end
	}
	return nil
}

func scopeTemplate(html string, scopeAttr string) (string, error) {
	var out strings.Builder
	for i := 0; i < len(html); {
		if html[i] != '<' || i+1 >= len(html) || html[i+1] == '/' || html[i+1] == '!' || html[i+1] == '?' {
			out.WriteByte(html[i])
			i++
			continue
		}

		end := findTagEnd(html, i+1)
		if end == -1 {
			line, col := lineCol(html, i)
			return "", fmt.Errorf("unclosed HTML tag at %d:%d", line, col)
		}

		out.WriteString(addScopeAttrToTag(html[i:end+1], scopeAttr))
		i = end + 1
	}
	return out.String(), nil
}

func findTagEnd(html string, start int) int {
	var quote byte
	escaped := false
	expressionDepth := 0
	for i := start; i < len(html); i++ {
		ch := html[i]
		if quote != 0 {
			if escaped {
				escaped = false
				continue
			}
			if ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' || (expressionDepth > 0 && ch == '`') {
			quote = ch
			continue
		}
		if ch == '{' {
			expressionDepth++
			continue
		}
		if ch == '}' && expressionDepth > 0 {
			expressionDepth--
			continue
		}
		if ch == '>' {
			if expressionDepth == 0 {
				return i
			}
		}
	}
	return -1
}

func addScopeAttrToTag(tag string, scopeAttr string) string {
	tagNameEnd := 1
	for tagNameEnd < len(tag) {
		ch := tag[tagNameEnd]
		if ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r' || ch == '/' || ch == '>' {
			break
		}
		tagNameEnd++
	}

	tagName := strings.ToLower(tag[1:tagNameEnd])
	if tagName == "script" || tagName == "style" {
		return tag
	}
	if regexp.MustCompile(`(?i)\s` + regexp.QuoteMeta(scopeAttr) + `(?:\s|=|>|/)`).MatchString(tag) {
		return tag
	}

	insertAt := len(tag) - 1
	if insertAt > 0 && tag[insertAt-1] == '/' {
		insertAt--
	}
	return tag[:insertAt] + ` ` + scopeAttr + tag[insertAt:]
}

func scopeCSS(css string, scopeAttr string) (string, error) {
	return scopeCSSBlock(css, scopeAttr, false)
}

func validateCSS(css string) error {
	_, err := scopeCSSBlock(css, "data-c-validate", false)
	return err
}

func scopeCSSBlock(css string, scopeAttr string, inKeyframes bool) (string, error) {
	var out strings.Builder
	for i := 0; i < len(css); {
		for i < len(css) && isWhitespace(css[i]) {
			i++
		}
		if i >= len(css) {
			break
		}

		headerStart := i
		open := findCSSOpenBrace(css, i)
		if open == -1 {
			remaining := strings.TrimSpace(css[i:])
			if remaining != "" {
				line, col := lineCol(css, i)
				return "", fmt.Errorf("CSS rule missing opening brace near %d:%d", line, col)
			}
			break
		}
		close := findMatchingBrace(css, open)
		if close == -1 {
			line, col := lineCol(css, open)
			return "", fmt.Errorf("unclosed CSS block for %q at %d:%d", strings.TrimSpace(css[headerStart:open]), line, col)
		}

		header := strings.TrimSpace(css[headerStart:open])
		body := strings.TrimSpace(css[open+1 : close])
		lowerHeader := strings.ToLower(header)

		if strings.HasPrefix(header, "@") {
			if strings.HasPrefix(lowerHeader, "@media") || strings.HasPrefix(lowerHeader, "@supports") || strings.HasPrefix(lowerHeader, "@container") || strings.HasPrefix(lowerHeader, "@layer") {
				out.WriteString(header)
				out.WriteString(" { ")
				scopedBody, err := scopeCSSBlock(body, scopeAttr, false)
				if err != nil {
					return "", err
				}
				out.WriteString(scopedBody)
				out.WriteString(" }\n")
			} else {
				out.WriteString(header)
				out.WriteString(" { ")
				out.WriteString(body)
				out.WriteString(" }\n")
			}
		} else if inKeyframes {
			out.WriteString(header)
			out.WriteString(" { ")
			out.WriteString(body)
			out.WriteString(" }\n")
		} else {
			out.WriteString(scopeSelectorList(header, scopeAttr))
			out.WriteString(" { ")
			out.WriteString(body)
			out.WriteString(" }\n")
		}

		i = close + 1
	}
	return strings.TrimSpace(out.String()), nil
}

func findCSSOpenBrace(css string, start int) int {
	var quote byte
	escaped := false
	for i := start; i < len(css); i++ {
		ch := css[i]
		if quote != 0 {
			if escaped {
				escaped = false
				continue
			}
			if ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' {
			quote = ch
			continue
		}
		if ch == '{' {
			return i
		}
	}
	return -1
}

func findMatchingBrace(css string, open int) int {
	depth := 0
	var quote byte
	escaped := false
	for i := open; i < len(css); i++ {
		ch := css[i]
		if quote != 0 {
			if escaped {
				escaped = false
				continue
			}
			if ch == '\\' {
				escaped = true
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' {
			quote = ch
			continue
		}
		if ch == '{' {
			depth++
		} else if ch == '}' {
			depth--
			if depth == 0 {
				return i
			}
		}
	}
	return -1
}

func scopeSelectorList(selectorList string, scopeAttr string) string {
	selectors := splitSelectorList(selectorList)
	var scoped []string
	for _, sel := range selectors {
		selTrim := strings.TrimSpace(sel)
		if selTrim == "" {
			continue
		}
		if strings.Contains(selTrim, ":global(") {
			scoped = append(scoped, unwrapGlobalSelector(selTrim))
		} else if strings.Contains(selTrim, ":host") {
			scoped = append(scoped, strings.ReplaceAll(selTrim, ":host", "["+scopeAttr+"]"))
		} else {
			scoped = append(scoped, appendScopeAttrToSelector(selTrim, scopeAttr))
		}
	}
	return strings.Join(scoped, ", ")
}

func appendScopeAttrToSelector(selector string, scopeAttr string) string {
	attr := "[" + scopeAttr + "]"
	trimmed := strings.TrimSpace(selector)
	if trimmed == "" {
		return trimmed
	}
	insertAt := len(trimmed)
	for i := len(trimmed) - 1; i >= 0; i-- {
		if trimmed[i] == ':' {
			insertAt = i
			if i > 0 && trimmed[i-1] == ':' {
				insertAt = i - 1
			}
			break
		}
	}
	if insertAt == len(trimmed) {
		return trimmed + attr
	}
	return trimmed[:insertAt] + attr + trimmed[insertAt:]
}

func splitSelectorList(selectorList string) []string {
	var parts []string
	var current strings.Builder
	depth := 0
	var quote byte
	for i := 0; i < len(selectorList); i++ {
		ch := selectorList[i]
		if quote != 0 {
			current.WriteByte(ch)
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '"' || ch == '\'' {
			quote = ch
			current.WriteByte(ch)
			continue
		}
		if ch == '(' || ch == '[' {
			depth++
		} else if ch == ')' || ch == ']' {
			depth--
		}
		if ch == ',' && depth == 0 {
			parts = append(parts, current.String())
			current.Reset()
			continue
		}
		current.WriteByte(ch)
	}
	parts = append(parts, current.String())
	return parts
}

func unwrapGlobalSelector(selector string) string {
	out := selector
	for {
		start := strings.Index(out, ":global(")
		if start == -1 {
			return out
		}
		contentStart := start + len(":global(")
		end := findSelectorParenEnd(out, contentStart-1)
		if end == -1 {
			return out
		}
		out = out[:start] + out[contentStart:end] + out[end+1:]
	}
}

func findSelectorParenEnd(input string, open int) int {
	depth := 0
	for i := open; i < len(input); i++ {
		if input[i] == '(' {
			depth++
		} else if input[i] == ')' {
			depth--
			if depth == 0 {
				return i
			}
		}
	}
	return -1
}

func isWhitespace(ch byte) bool {
	return ch == ' ' || ch == '\n' || ch == '\t' || ch == '\r'
}

func hasBooleanAttr(attrs string, name string) bool {
	re := regexp.MustCompile(`(?i)(^|\s)` + regexp.QuoteMeta(name) + `(\s|=|$)`)
	return re.MatchString(attrs)
}

func sanitizeScopeID(name string) string {
	var out strings.Builder
	for _, r := range strings.ToLower(name) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			out.WriteRune(r)
		} else {
			out.WriteByte('-')
		}
	}
	id := strings.Trim(out.String(), "-")
	if id == "" {
		return "component"
	}
	return id
}

func uppercaseFirst(str string) string {
	if len(str) == 0 {
		return ""
	}
	return strings.ToUpper(str[:1]) + str[1:]
}

func indentLines(str string, indent string) string {
	lines := strings.Split(str, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = indent + line
		}
	}
	return strings.Join(lines, "\n")
}
