// Generated by CachouJS Compiler - DO NOT EDIT
// Source: ActivityPanel.cachou
import * as Cachou from "cachoujs";
import "./ActivityPanel.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function ActivityPanel(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<section class="activity-panel" data-c-activitypanel>
  ${mapArray(props.activities, item => html`<article data-c-activitypanel>
    <time data-c-activitypanel>${item.due}</time>
    <strong data-c-activitypanel>${item.title}</strong>
    <p data-c-activitypanel>${item.contact}</p>
    <button class="ghost" disabled=${() => item.due === "Done"} onclick=${() => props.completeActivity(item)} data-c-activitypanel>Complete</button>
  </article>`, item => item.id, { uniqueKeys: true, reactiveItems: false })}
</section>
`;
}
//# sourceMappingURL=ActivityPanel.js.map
