// Generated by CachouJS Compiler - DO NOT EDIT
// Source: CollaborationLab.cachou
import * as Cachou from "cachoujs";
import "./CollaborationLab.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function CollaborationLab(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<section class="collab" data-c-collaborationlab>
  <header data-c-collaborationlab>
    <span data-c-collaborationlab>Concurrency proof</span>
    <h2 data-c-collaborationlab>Two editors, one server version</h2>
  </header>
  <div class="columns" data-c-collaborationlab>
    <article data-c-collaborationlab>
      <strong data-c-collaborationlab>Editor A</strong>
      <p data-c-collaborationlab>${props.editorA}</p>
    </article>
    <article data-c-collaborationlab>
      <strong data-c-collaborationlab>Editor B</strong>
      <p data-c-collaborationlab>${props.editorB}</p>
    </article>
    <article data-c-collaborationlab>
      <strong data-c-collaborationlab>Server state</strong>
      <p data-c-collaborationlab>${props.serverState}</p>
    </article>
  </div>
  <button onclick=${props.runLab} disabled=${props.running} data-c-collaborationlab>${() => props.running() ? "Running..." : "Run conflict demo"}</button>
  <ul data-c-collaborationlab>
    ${props.log().map((item, index) => html`<li data-c-collaborationlab>
      <strong data-c-collaborationlab>${index + 1}. ${item.title}</strong>
      <p data-c-collaborationlab>${item.detail}</p>
    </li>`)}
  </ul>
</section>
`;
}
//# sourceMappingURL=CollaborationLab.js.map
