// Generated by CachouJS Compiler - DO NOT EDIT
// Source: HeroTile.cachou
import * as Cachou from "cachoujs";
import "./HeroTile.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function HeroTile(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<article class="hero-tile" data-c-herotile>
  <span data-c-herotile>${props.label}</span>
  <strong data-c-herotile>${props.value}</strong>
</article>
`;
}
//# sourceMappingURL=HeroTile.js.map
