// Generated by CachouJS Compiler - DO NOT EDIT
// Source: OverviewPanel.cachou
import * as Cachou from "cachoujs";
import "./OverviewPanel.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function OverviewPanel(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<section class="overview-grid" data-c-overviewpanel>
  <article class="spotlight" data-c-overviewpanel>
    <header data-c-overviewpanel>
      <div data-c-overviewpanel>
        <span data-c-overviewpanel>Focus list</span>
        <h2 data-c-overviewpanel>Accounts needing attention</h2>
      </div>
      <button class="ghost" onclick=${props.openContacts} data-c-overviewpanel>Open contacts</button>
    </header>
    <div class="priority-list" data-c-overviewpanel>
      ${mapArray(props.hotContacts, contact => props.PriorityCard({
        initial: contact.name.slice(0, 1),
        name: contact.name,
        company: contact.company,
        status: contact.status,
        onSelect: () => props.selectContact(contact)
      }), contact => contact.id, { uniqueKeys: true, reactiveItems: false })}
    </div>
  </article>

  <article class="insights" data-c-overviewpanel>
    <header data-c-overviewpanel>
      <span data-c-overviewpanel>Owner load</span>
      <h2 data-c-overviewpanel>Coverage</h2>
    </header>
    ${mapArray(props.ownerLoad, item => html`<div class="bar-row" data-c-overviewpanel>
      <span data-c-overviewpanel>${item.owner}</span>
      <div data-c-overviewpanel><i style=${props.ownerBarStyle(item)} data-c-overviewpanel></i></div>
      <strong data-c-overviewpanel>${item.count}</strong>
    </div>`, item => item.owner, { uniqueKeys: true, reactiveItems: false })}
  </article>

  <article class="spotlight wide" data-c-overviewpanel>
    <header data-c-overviewpanel>
      <div data-c-overviewpanel>
        <span data-c-overviewpanel>Pipeline health</span>
        <h2 data-c-overviewpanel>Stage distribution</h2>
      </div>
      <button class="ghost" onclick=${props.openPipeline} data-c-overviewpanel>Open pipeline</button>
    </header>
    <div class="mini-pipeline" data-c-overviewpanel>
      ${mapArray(props.pipeline, column => props.StageTile({
        stage: column.stage,
        count: column.deals.length
      }), column => column.stage, { uniqueKeys: true, reactiveItems: false })}
    </div>
  </article>
</section>
`;
}
//# sourceMappingURL=OverviewPanel.js.map
