// Generated by CachouJS Compiler - DO NOT EDIT
// Source: PerformanceLab.cachou
import * as Cachou from "cachoujs";
import "./PerformanceLab.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function PerformanceLab(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<section class="lab" data-c-performancelab>
  <header data-c-performancelab>
    <span data-c-performancelab>Performance Lab</span>
    <h2 data-c-performancelab>CRM-scale runtime proof</h2>
  </header>
  <div class="lab-grid" data-c-performancelab>
    <article data-c-performancelab><span data-c-performancelab>Contacts rendered</span><strong data-c-performancelab>${props.contactsCount}</strong></article>
    <article data-c-performancelab><span data-c-performancelab>Pipeline stages</span><strong data-c-performancelab>${props.stageCount}</strong></article>
    <article data-c-performancelab><span data-c-performancelab>Realtime messages</span><strong data-c-performancelab>${props.messageCount}</strong></article>
    <article data-c-performancelab><span data-c-performancelab>Last local load</span><strong data-c-performancelab>${props.lastLoadMs}</strong></article>
  </div>
  <div class="actions" data-c-performancelab>
    <button onclick=${props.loadStressContacts} data-c-performancelab>Load 5,000 contacts</button>
    <button class="ghost" onclick=${props.measureRouteChurn} data-c-performancelab>Route churn x40</button>
  </div>
</section>
`;
}
//# sourceMappingURL=PerformanceLab.js.map
