// Generated by CachouJS Compiler - DO NOT EDIT
// Source: PriorityCard.cachou
import * as Cachou from "cachoujs";
import "./PriorityCard.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function PriorityCard(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<button class="sfc-priority-card" onclick=${props.onSelect} data-c-prioritycard>
  <span class="sfc-avatar" data-c-prioritycard>${props.initial}</span>
  <span class="identity" data-c-prioritycard>
    <strong data-c-prioritycard>${props.name}</strong>
    <small data-c-prioritycard>${props.company}</small>
  </span>
  <em data-c-prioritycard>${props.status}</em>
</button>
`;
}
//# sourceMappingURL=PriorityCard.js.map
