// Generated by CachouJS Compiler - DO NOT EDIT
// Source: StageTile.cachou
import * as Cachou from "cachoujs";
import "./StageTile.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function StageTile(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<div class="stage-tile" data-c-stagetile>
  <strong data-c-stagetile>${props.stage}</strong>
  <span data-c-stagetile>${props.count}</span>
</div>
`;
}
//# sourceMappingURL=StageTile.js.map
