// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: ActivityPanel.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./ActivityPanel.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function ActivityPanel(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<section class="activity-panel" data-c-activitypanel>
  ${mapArray(props.activities, item => html`<article data-c-activitypanel>
    <time data-c-activitypanel>${item.due}</time>
    <strong data-c-activitypanel>${item.title}</strong>
    <p data-c-activitypanel>${item.contact}</p>
    <button class="ghost" disabled=${() => item.due === "Done"} onclick=${() => props.completeActivity(item)} data-c-activitypanel>Complete</button>
  </article>`, item => item.id, { uniqueKeys: true, reactiveItems: false })}
</section>
`;
}
//# sourceMappingURL=ActivityPanel.js.map
