// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: CompaniesPanel.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./CompaniesPanel.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function CompaniesPanel(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<section class="companies" data-c-companiespanel>
  <div class="list" data-c-companiespanel>
    ${mapArray(props.companies, company => html`<button
      class=${() => props.selectedCompany()?.id === company.id ? "row selected" : "row"}
      onclick=${() => props.setSelectedCompanyId(company.id)}
     data-c-companiespanel>
      <strong data-c-companiespanel>${company.name}</strong>
      <small data-c-companiespanel>${company.segment} - ${company.owner}</small>
    </button>`, company => company.id, { uniqueKeys: true, reactiveItems: false })}
  </div>
  <div class="detail" data-c-companiespanel>
    ${props.selectedCompany() ? props.renderDetail(props.selectedCompany()) : html`<p data-c-companiespanel>Select a company.</p>`}
  </div>
</section>
`;
}
//# sourceMappingURL=CompaniesPanel.js.map
