// Generated by CachouJS Compiler - DO NOT EDIT
// Source: ContactsPanel.cachou
import * as Cachou from "cachoujs";
import "./ContactsPanel.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function ContactsPanel(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<section class="split" data-c-contactspanel>
  <div class="list" data-c-contactspanel>
    ${props.visibleContacts().length === 0 ? html`<div class="empty" data-c-contactspanel>No contacts match this search.</div>` : null}
    ${mapArray(props.visibleContacts, contact => html`<button
      class=${() => props.selectedContact()?.id === contact.id ? "row selected" : "row"}
      onclick=${() => props.setSelectedId(contact.id)}
     data-c-contactspanel>
      <span data-c-contactspanel>
        <strong data-c-contactspanel>${contact.name}</strong>
        <small data-c-contactspanel>${contact.company}</small>
      </span>
      <em data-c-contactspanel>${contact.status}</em>
    </button>`, contact => contact.id, { uniqueKeys: true, reactiveItems: false })}
  </div>
  <article class="detail" data-c-contactspanel>
    ${props.selectedContact() ? props.renderDetail(props.selectedContact()) : html`<div class="empty" data-c-contactspanel>Select a contact.</div>`}
  </article>
</section>
`;
}
//# sourceMappingURL=ContactsPanel.js.map
