// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: ContactsPanel.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./ContactsPanel.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function ContactsPanel(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<section class="split" data-c-contactspanel>
  <div class="list" onscroll=${props.onContactScroll} data-c-contactspanel>
    ${props.visibleContacts().length === 0 ? html`<div class="empty" data-c-contactspanel>No contacts match this search.</div>` : null}
    <div class="virtual-content" style=${() => "height:" + props.visibleContactHeight() + "px"} data-c-contactspanel>
      ${mapArray(props.visibleContacts, (contact, index) => html`<button
        class=${() => props.selectedContact()?.id === contact.id ? "row selected" : "row"}
        style=${() => "top:" + ((props.visibleContactStart() + index) * 74) + "px"}
        onclick=${() => props.setSelectedId(contact.id)}
       data-c-contactspanel>
        <span data-c-contactspanel>
          <strong data-c-contactspanel>${contact.name}</strong>
          <small data-c-contactspanel>${contact.company}</small>
        </span>
        <em data-c-contactspanel>${contact.status}</em>
      </button>`, contact => contact.id, { uniqueKeys: true, reactiveItems: false })}
    </div>
  </div>
  <article class="detail" data-c-contactspanel>
    ${props.selectedContact() ? props.renderDetail(props.selectedContact()) : html`<div class="empty" data-c-contactspanel>Select a contact.</div>`}
  </article>
</section>
`;
}
//# sourceMappingURL=ContactsPanel.js.map
