// Generated by CachouJS Compiler - DO NOT EDIT
// Source: DealEditor.cachou
import * as Cachou from "cachoujs";
import "./DealEditor.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function DealEditor(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<div class="modal" role="dialog" aria-modal="true" aria-label="Deal editor" data-c-dealeditor>
  <form class="editor" onsubmit=${props.persistDeal} data-c-dealeditor>
    <header data-c-dealeditor>
      <h2 data-c-dealeditor>${props.current.name ? "Edit deal" : "New deal"}</h2>
      <button type="button" class="icon" aria-label="Close deal editor" onclick=${props.close} data-c-dealeditor>x</button>
    </header>
    <label data-c-dealeditor>Name<input value=${props.current.name} oninput=${event => props.setDraft({ ...props.draft(), name: event.target.value })}  data-c-dealeditor/></label>
    <label data-c-dealeditor>Company<input value=${props.current.company} oninput=${event => props.setDraft({ ...props.draft(), company: event.target.value })}  data-c-dealeditor/></label>
    <label data-c-dealeditor>Value<input type="number" value=${props.current.value} oninput=${event => props.setDraft({ ...props.draft(), value: Number(event.target.value || 0) })}  data-c-dealeditor/></label>
    <label data-c-dealeditor>Stage<select value=${props.current.stage} onchange=${event => props.setDraft({ ...props.draft(), stage: event.target.value })} data-c-dealeditor>
      ${props.stages.map(stage => html`<option value=${stage} data-c-dealeditor>${stage}</option>`)}
    </select></label>
    <footer data-c-dealeditor>
      <button type="button" class="ghost" onclick=${props.close} data-c-dealeditor>Cancel</button>
      <button disabled=${props.busy} data-c-dealeditor>${() => props.busy() ? "Saving..." : "Save deal"}</button>
    </footer>
  </form>
</div>
`;
}
//# sourceMappingURL=DealEditor.js.map
