// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: HeroTile.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./HeroTile.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function HeroTile(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<article class="hero-tile" data-c-herotile>
  <span data-c-herotile>${props.label}</span>
  <strong data-c-herotile>${props.value}</strong>
</article>
`;
}
//# sourceMappingURL=HeroTile.js.map
