// Generated by CachouJS Compiler - DO NOT EDIT
// Source: LiveRoomPanel.cachou
import * as Cachou from "cachoujs";
import "./LiveRoomPanel.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useHead,
  Show,
  Switch,
  Match
} = Cachou;

export default function LiveRoomPanel(props = {}) {
  // --- Component Setup ---
  

  // --- Render ---
  return html`
<section class="live-room" data-c-liveroompanel>
  <article class="chat-panel" data-c-liveroompanel>
    <header data-c-liveroompanel>
      <div data-c-liveroompanel>
        <span data-c-liveroompanel>Realtime team room</span>
        <h2 data-c-liveroompanel>Deal desk chat</h2>
      </div>
      <strong class=${() => props.chatStatus() === "live" ? "live-pill online" : "live-pill"} data-c-liveroompanel>${props.chatStatus}</strong>
    </header>
    <div class="messages" data-c-liveroompanel>
      ${mapArray(props.chatMessages, message => html`<div class="message" data-c-liveroompanel>
        <span class="avatar" data-c-liveroompanel>${message.author.slice(0, 1)}</span>
        <div data-c-liveroompanel>
          <header data-c-liveroompanel>
            <strong data-c-liveroompanel>${message.author}</strong>
            <time data-c-liveroompanel>${new Date(message.createdAt || Date.now()).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time>
          </header>
          <p data-c-liveroompanel>${message.text}</p>
        </div>
      </div>`, message => message.id, { uniqueKeys: true, reactiveItems: false })}
    </div>
    <form class="composer" onsubmit=${props.sendChat} data-c-liveroompanel>
      <input
        aria-label="Message"
        placeholder="Send a realtime update"
        value=${props.chatDraft}
        oninput=${event => props.setChatDraft(event.target.value)}
       data-c-liveroompanel/>
      <button disabled=${() => props.chatStatus() !== "live"} data-c-liveroompanel>Send</button>
    </form>
  </article>
  <aside class="presence-panel" data-c-liveroompanel>
    <span data-c-liveroompanel>Live operators</span>
    <h2 data-c-liveroompanel>3 active</h2>
    <div class="presence" data-c-liveroompanel><i data-c-liveroompanel></i><strong data-c-liveroompanel>Sales</strong><small data-c-liveroompanel>Watching pipeline</small></div>
    <div class="presence" data-c-liveroompanel><i data-c-liveroompanel></i><strong data-c-liveroompanel>Support</strong><small data-c-liveroompanel>Customer handoff</small></div>
    <div class="presence" data-c-liveroompanel><i data-c-liveroompanel></i><strong data-c-liveroompanel>Ops</strong><small data-c-liveroompanel>Database monitor</small></div>
  </aside>
</section>
`;
}
//# sourceMappingURL=LiveRoomPanel.js.map
