// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: LoginPanel.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./LoginPanel.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function LoginPanel(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<form class="login-card" onsubmit=${props.signIn} data-c-loginpanel>
  <span data-c-loginpanel>Cachou CRM</span>
  <h1 data-c-loginpanel>Sign in</h1>
  <p class="status-line" data-c-loginpanel><i class=${props.systemOnline() ? "dot online" : "dot"} data-c-loginpanel></i>${props.systemMode()}</p>
  <label data-c-loginpanel>Username<input value=${() => props.loginDraft().username} oninput=${event => props.setLoginDraft({ ...props.loginDraft(), username: event.target.value })}  data-c-loginpanel/></label>
  <label data-c-loginpanel>Password<input type="password" value=${() => props.loginDraft().password} oninput=${event => props.setLoginDraft({ ...props.loginDraft(), password: event.target.value })}  data-c-loginpanel/></label>
  <div class="login-shortcuts" data-c-loginpanel>
    ${props.accounts.map(username => html`<button type="button" class="ghost" onclick=${() => props.setLoginDraft({ username, password: username })} data-c-loginpanel>${username}</button>`)}
  </div>
  ${props.loginError() ? html`<p class="error-text" data-c-loginpanel>${props.loginError}</p>` : null}
  <button disabled=${props.loginBusy} data-c-loginpanel>${() => props.loginBusy() ? "Signing in..." : "Sign in"}</button>
</form>
`;
}
//# sourceMappingURL=LoginPanel.js.map
