// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: MetricCard.cachou
import * as Cachou from "cachoujs";
import "./MetricCard.css";

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function MetricCard(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<section class="metric-card" data-c-metriccard>
  <span data-c-metriccard>${props.label}</span>
  <strong data-c-metriccard>${props.value}</strong>
</section>
`;
}
//# sourceMappingURL=MetricCard.js.map
