// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: PipelineBoard.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./PipelineBoard.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function PipelineBoard(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<section class="pipeline-board" data-c-pipelineboard>
  ${mapArray(props.pipeline, column => html`<article
    class="stage"
    ondragover=${props.allowDrop}
    ondragleave=${props.clearDrop}
    ondrop=${event => props.dropDeal(event, column.stage)}
   data-c-pipelineboard>
    <header data-c-pipelineboard>
      <strong data-c-pipelineboard>${column.stage}</strong>
      <span data-c-pipelineboard>${column.deals.length}</span>
    </header>
    ${column.deals.length === 0 ? html`<div class="empty-zone" data-c-pipelineboard>Drop a deal here</div>` : null}
    ${column.deals.map(deal => html`<div
      class="deal"
      draggable=${true}
      role="group"
      tabindex="0"
      aria-label=${`${deal.name}, ${deal.company}, ${deal.stage}. Use arrow keys to move stage.`}
      ondragstart=${event => props.dragDeal(event, deal.id)}
      onkeydown=${event => props.keyboardDeal(event, deal)}
     data-c-pipelineboard>
      <div data-c-pipelineboard>
        <strong data-c-pipelineboard>${deal.name}</strong>
        <small data-c-pipelineboard>${deal.company}</small>
      </div>
      <span data-c-pipelineboard>${props.formatCurrency(Number(deal.value || 0))}</span>
      <button
        class="ghost mini"
        disabled=${() => deal.stage === "Lost" || !props.canMoveDeals()}
        onclick=${() => props.moveDeal(deal.id, props.nextStage(deal.stage))}
       data-c-pipelineboard>Move</button>
      <button
        class="ghost mini"
        disabled=${() => !props.canMoveDeals()}
        onclick=${() => props.editDeal(deal)}
       data-c-pipelineboard>Edit</button>
    </div>`)}
  </article>`, column => column.stage, { uniqueKeys: true, reactiveItems: false })}
</section>
`;
}
//# sourceMappingURL=PipelineBoard.js.map
