// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: PriorityCard.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./PriorityCard.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function PriorityCard(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<button class="sfc-priority-card" onclick=${props.onSelect} data-c-prioritycard>
  <span class="sfc-avatar" data-c-prioritycard>${props.initial}</span>
  <span class="identity" data-c-prioritycard>
    <strong data-c-prioritycard>${props.name}</strong>
    <small data-c-prioritycard>${props.company}</small>
  </span>
  <em data-c-prioritycard>${props.status}</em>
</button>
`;
}
//# sourceMappingURL=PriorityCard.js.map
