// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: SecurityPanel.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./SecurityPanel.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function SecurityPanel(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<div class="security-grid" data-c-securitypanel>
  <section data-c-securitypanel>
    <span data-c-securitypanel>RBAC matrix</span>
    <h2 data-c-securitypanel>Roles and permissions</h2>
    ${mapArray(props.users, user => html`<article data-c-securitypanel>
      <strong data-c-securitypanel>${user.name}</strong>
      <small data-c-securitypanel>${user.role}${user.disabled ? " - disabled" : ""} - ${user.sessionCount || 0} sessions</small>
      <p data-c-securitypanel>${(user.permissions || []).join(", ")}</p>
      <div class="actions" data-c-securitypanel>
        <button class="ghost" onclick=${() => props.editUser(user)} data-c-securitypanel>Edit</button>
        <button class="ghost" onclick=${() => props.toggleUser(user)} data-c-securitypanel>${user.disabled ? "Enable" : "Disable"}</button>
        <button class="ghost" onclick=${() => props.revokeSessions(user)} data-c-securitypanel>Revoke sessions</button>
      </div>
    </article>`, user => user.id, { uniqueKeys: true, reactiveItems: false })}
    <form onsubmit=${props.saveUser} data-c-securitypanel>
      <strong data-c-securitypanel>Admin user management</strong>
      <label data-c-securitypanel>Username<input value=${() => props.userDraft().username} oninput=${event => props.setUserDraft({ ...props.userDraft(), username: event.target.value })}  data-c-securitypanel/></label>
      <label data-c-securitypanel>Name<input value=${() => props.userDraft().name} oninput=${event => props.setUserDraft({ ...props.userDraft(), name: event.target.value })}  data-c-securitypanel/></label>
      <label data-c-securitypanel>Role<select value=${() => props.userDraft().role} onchange=${event => props.setUserDraft({ ...props.userDraft(), role: event.target.value })} data-c-securitypanel>
        <option value="Sales" data-c-securitypanel>Sales</option>
        <option value="Manager" data-c-securitypanel>Manager</option>
        <option value="Admin" data-c-securitypanel>Admin</option>
      </select></label>
      <label data-c-securitypanel>Password<input type="password" value=${() => props.userDraft().password} oninput=${event => props.setUserDraft({ ...props.userDraft(), password: event.target.value })}  data-c-securitypanel/></label>
      <div class="actions" data-c-securitypanel>
        <button data-c-securitypanel>Save user</button>
        <button type="button" class="ghost" onclick=${props.resetDemo} data-c-securitypanel>Reset demo</button>
      </div>
    </form>
    <div class="diagnostics" data-c-securitypanel>
      <strong data-c-securitypanel>Database diagnostics</strong>
      <small data-c-securitypanel>${props.diagnostics?.mode || "loading"}</small>
      <code data-c-securitypanel>${props.formatRows(props.diagnostics)}</code>
      <code data-c-securitypanel>${props.formatTyped(props.diagnostics)}</code>
    </div>
    <div class="ops-grid" data-c-securitypanel>
      <strong data-c-securitypanel>API operations</strong>
      <small data-c-securitypanel>${props.opsMetrics ? `${props.opsMetrics.websocketClients || 0} websocket clients` : "loading"}</small>
      <article data-c-securitypanel>
        <span data-c-securitypanel>Requests</span>
        <strong data-c-securitypanel>${props.opsMetrics?.requestsTotal || 0}</strong>
      </article>
      <article data-c-securitypanel>
        <span data-c-securitypanel>Avg latency</span>
        <strong data-c-securitypanel>${props.opsMetrics?.averageDurationMs || 0}ms</strong>
      </article>
      <article data-c-securitypanel>
        <span data-c-securitypanel>Inflight</span>
        <strong data-c-securitypanel>${props.opsMetrics?.inflight || 0}</strong>
      </article>
      <article data-c-securitypanel>
        <span data-c-securitypanel>Sessions</span>
        <strong data-c-securitypanel>${props.opsMetrics?.sessionsCached || 0}</strong>
      </article>
      <code data-c-securitypanel>${props.formatOpsRoutes(props.opsMetrics)}</code>
    </div>
  </section>
  <section data-c-securitypanel>
    <span data-c-securitypanel>Audit stream</span>
    <h2 data-c-securitypanel>Timeline</h2>
    <div class="filters" data-c-securitypanel>
      <label data-c-securitypanel>Actor<input value=${() => props.auditFilter().actor} oninput=${event => props.setAuditFilter({ ...props.auditFilter(), actor: event.target.value })}  data-c-securitypanel/></label>
      <label data-c-securitypanel>Action<input value=${() => props.auditFilter().action} oninput=${event => props.setAuditFilter({ ...props.auditFilter(), action: event.target.value })}  data-c-securitypanel/></label>
      <label data-c-securitypanel>Role<select value=${() => props.auditFilter().role} onchange=${event => props.setAuditFilter({ ...props.auditFilter(), role: event.target.value })} data-c-securitypanel>
        <option value="" data-c-securitypanel>Any role</option>
        <option value="Sales" data-c-securitypanel>Sales</option>
        <option value="Manager" data-c-securitypanel>Manager</option>
        <option value="Admin" data-c-securitypanel>Admin</option>
        <option value="Guest" data-c-securitypanel>Guest</option>
      </select></label>
      <button class="ghost" onclick=${props.exportAudit} data-c-securitypanel>Export audit log</button>
    </div>
    <div class="timeline" data-c-securitypanel>
      ${mapArray(props.audit, item => html`<article data-c-securitypanel>
        <strong data-c-securitypanel>${props.auditTitle(item)}</strong>
        <small data-c-securitypanel>${item.actor} - ${item.role}</small>
        <time data-c-securitypanel>${new Date(item.createdAt || Date.now()).toLocaleString()}</time>
        <p data-c-securitypanel>${props.auditDescription(item)}</p>
      </article>`, item => item.id, { uniqueKeys: true, reactiveItems: false })}
    </div>
  </section>
</div>
`;
}
//# sourceMappingURL=SecurityPanel.js.map
