// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: StageTile.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./StageTile.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function StageTile(props = {}) {
  // --- Component Setup ---


  // --- Render ---
  return html`
<div class="stage-tile" data-c-stagetile>
  <strong data-c-stagetile>${props.stage}</strong>
  <span data-c-stagetile>${props.count}</span>
</div>
`;
}
//# sourceMappingURL=StageTile.js.map
