// Generated by CachouJS Compiler (JS) - DO NOT EDIT
// Source: StatCard.cachou
import * as Cachou from "cachoujs";
if (typeof document !== "undefined") import("./StatCard.css");

const {
  signal,
  effect,
  createRoot,
  memo,
  store,
  batch,
  onCleanup,
  onMount,
  untrack,
  getOwner,
  runWithOwner,
  html,
  mapArray,
  createResource,
  htmlStatic,
  Router,
  Route,
  Layout,
  Outlet,
  Link,
  navigate,
  getPath,
  getQueryParams,
  getRouteData,
  useRouteData,
  useParams,
  useSearchParams,
  useHead,
  Show,
  Switch,
  Match,
  For,
  Index,
  splitProps,
  mergeProps,
  Dynamic,
  createAction,
  redirect,
  notFound,
  createMutation,
  persist,
  Dialog
} = Cachou;

export default function StatCard(props = {}) {
  // --- Component Setup ---
  // StatCard shows a reactive value, title, and description

  // --- Render ---
  return html`
<div class="card" data-c-statcard>
  <div class="card-title" data-c-statcard>
    ${props.title}
    <span data-c-statcard>${props.value}</span>
  </div>
  <p style="color: var(--text-muted); font-size: 14px;" data-c-statcard>${props.description}</p>
</div>
`;
}
//# sourceMappingURL=StatCard.js.map
